language: node_js
node_js:
  - "10"

install:
  - yarn

test: true

script:
  - yarn fix
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ef5806c3bbd0dde9f8ce3241a53050fda2b31528  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master